/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.math.BigInteger;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Administrator
 */
public class RSAA extends javax.swing.JFrame {

    /**
     * Creates new form RSAA
     */
    public RSAA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtvanban = new javax.swing.JTextField();
        txtkey = new javax.swing.JTextField();
        txtmahoa = new javax.swing.JTextField();
        txtgiama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnkey = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtvanban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvanbanActionPerformed(evt);
            }
        });

        txtmahoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmahoaActionPerformed(evt);
            }
        });

        txtgiama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgiamaActionPerformed(evt);
            }
        });

        jButton1.setText("ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("plaintext");

        jLabel2.setText("khoa");

        jLabel3.setText("encrypt");

        jLabel4.setText("decrypt");

        btnkey.setText("key");
        btnkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnkey))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtgiama, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                        .addComponent(txtmahoa)
                        .addComponent(txtkey)
                        .addComponent(txtvanban)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvanban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmahoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgiama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnkey))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmahoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmahoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmahoaActionPerformed

    private void txtgiamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgiamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgiamaActionPerformed

    private void txtvanbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvanbanActionPerformed
        // TODO add your handling code here:
        BigInteger[] ciphertext = null;
        BigInteger n = null;
        BigInteger d = null;
        
        RSA rsa = new RSA(8);
        n= rsa.getN();
        d=rsa.getD();
        ciphertext = rsa.encrypt(txtvanban.getText());
        StringBuffer bf =new StringBuffer();
        for(int i=0;i<ciphertext.length;i++){
            bf.append(ciphertext[i].toString(16).toUpperCase());
            if(i!= ciphertext.length-1)
                System.out.println(" ");
        }
        String message = bf.toString();
        
        String dhash = rsa.decrypt(ciphertext, d, n);
       
        txtvanban.setText(message);
    }//GEN-LAST:event_txtvanbanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        BigInteger[] ciphertext = null;
        BigInteger n = null;
        BigInteger d = null;
        
        RSA rsa = new RSA(8);
        n= rsa.getN();
        d=rsa.getD();
        ciphertext = rsa.encrypt(txtvanban.getText());
        StringBuilder bf =new StringBuilder();
        for(int i=0;i<ciphertext.length;i++){
            bf.append(ciphertext[i].toString(16).toUpperCase());
            if(i!= ciphertext.length-1)
                System.out.println(" ");
        }
        String message = bf.toString();
        
        String dhash = rsa.decrypt(ciphertext, d, n);
       
        txtkey.setText(message);
        txtmahoa.setText(dhash);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeyActionPerformed
        // TODO add your handling code here:
         
        try {
            
    KeyPairGenerator kpg;    
    kpg = KeyPairGenerator.getInstance("RSA");
    kpg.initialize(1024);
    KeyPair kp=kpg.genKeyPair();
    PublicKey pbkey =kp.getPublic();
    PrivateKey prkey=kp.getPrivate();
    FileOutputStream f1 =new FileOutputStream("C:\\Users\\Administrator\\Desktop\\Skey_RSA_pub.dat");
    ObjectOutputStream b1 = new ObjectOutputStream(f1);
    b1.writeObject(pbkey);
    FileOutputStream f2 = new FileOutputStream("C:\\Users\\Administrator\\Desktop\\Skey_RSA_priv.dat");
    ObjectOutputStream b2 =new ObjectOutputStream(f2);
    b2.writeObject(prkey); 
   
        } catch (Exception ex) {
            Logger.getLogger(RSAA.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btnkeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RSAA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RSAA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RSAA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RSAA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RSAA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkey;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtgiama;
    private javax.swing.JTextField txtkey;
    private javax.swing.JTextField txtmahoa;
    private javax.swing.JTextField txtvanban;
    // End of variables declaration//GEN-END:variables
}
